// export const ShopActionTypes = {
//     UPDATE_COLLECTIONS: "UPDATE_COLLECTIONS"
//   };

// Redux Thunk approach
export const ShopActionTypes = {
    FETCH_COLLECTIONS_START: "FETCH_COLLECTIONS_START",
    FETCH_COLLECTIONS_SUCCESS: 'FETCH_COLLECTIONS_SUCCESS',
    FETCH_COLLECTIONS_FAILURE: 'FETCH_COLLECTIONS_FAILURE'
  };
  